kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin